# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Build backend
      run: |
        cd $GITHUB_WORKSPACE
        docker build -t qdrant/site-search:${{ github.sha }} .
        docker save -o qdrant-site-search.tar qdrant/site-search:${{ github.sha }}
        ls -al .
    
    - name: copy data with ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        source: "qdrant-site-search.tar"
        target: "deployment/data"

    - name: run images
      uses: fifsky/ssh-action@master
      with:
        command: |
          docker load -i deployment/data/qdrant-site-search.tar;
          docker images;
          docker kill qdrant-site-search || true;
          docker rm qdrant-site-search || true;
          docker run -d -p 8005:8005 --restart unless-stopped --network=qdrant-net -e QDRANT_HOST=${{ secrets.QDRANT_HOST }} -e QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }} --name qdrant-site-search qdrant/site-search:${{ github.sha }};
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
